- name: Create Docker volumes for SonarQube
  command: docker volume create {{ item }}
  with_items:
    - sonarqube_conf
    - sonarqube_data
    - sonarqube_logs
    - sonarqube_extensions
    - postgresql

- name: Pull PostgreSQL image
  docker_image:
    name: postgres
    tag: "13"
    source: pull

- name: Run PostgreSQL container
  docker_container:
    name: sonarqube_db
    image: postgres:13
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql:/var/lib/postgresql/data

- name: Pull SonarQube image
  docker_image:
    name: sonarqube
    tag: "latest"
    source: pull

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:latest
    state: started
    restart_policy: always
    env:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    links:
      - sonarqube_db

